"""Emit the app-driven test programs from the generated layouts.

Shared skeleton, per-test body. Every file is a complete standalone MakeCode
program: paste, flash, press Connect, and its panel appears by itself.

Three rules carried over from main.ts, each learned the hard way there:

  1. The CFG burst runs from basic.forever, NEVER from onUartDataReceived.
     Sending it inside the receive callback blocks the BLE stack for the whole
     transfer and the handshake never completes.
  2. Tests touching P3/P4/P10 (line sensors) or P7 (strip) must call
     led.enable(false) -- those are LED-matrix pins. Those tests report through
     the headlights instead of the display.
  3. Telemetry that does not change is not sent. These run on a radio that has
     to stay responsive for the controls.

API calls are taken from the existing standalone tests, which are already
known to compile in MakeCode, rather than from main.ts where they are wrapped
in layers of state.
"""
import re, os

HERE = os.path.dirname(os.path.abspath(__file__))

B64 = {}
for block in open(f"{HERE}/layouts_b64.txt", encoding="utf-8").read().split("### ")[1:]:
    name, rest = block.split("\n", 1)
    B64[name.strip()] = "".join(rest.split())

SKEL = '''/**
 * TEST: %(TITLE)s, DRIVEN FROM THE APP - flash this alone.
 *
 * Extensions: %(EXT)s
 *
 * The app-driven twin of %(TWIN)s. That one runs a fixed sequence while you
 * watch; this one hands the subsystem to a child through the phone.
 *
 * Open the app, press Connect, and the %(PANEL)s panel appears by itself. The
 * layout lives in this file and is sent over the link -- nothing to import.
 *
 * PASS: %(PASS)s
 * FAIL: panel never appears -> run test-app-ble.ts first. That is a link
 *                             fault, not a %(THING)s fault.
 *       panel appears but nothing happens -> run %(TWIN)s, which removes
 *                             Bluetooth from the picture entirely.
 */

// Generated by tests/gen_test_layouts.py. Widget ids match main.ts on purpose,
// so the handlers below are the real ones rather than lookalikes.
const CFG = "%(CFG)s"

bluetooth.startUartService()
bluetooth.setTransmitPower(7)
%(MATRIX)s
let cfgWanted = false
let cfgTxPos = 0
let cfgTxActive = false
let cfgTxNextAt = 0
let nextPollAt = 0
const CFG_TX_GAP_MS = 35
const POLL_MS = %(POLL)d

%(HELPERS)s// Only ever sets flags and drives hardware. The CFG burst is NOT sent from
// here -- see the forever loop below.
bluetooth.onUartDataReceived(serial.delimiters(Delimiters.NewLine), function () {
    let cmd = bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine))
    // Chained if/else-if with no `return` inside this lambda, matching the
    // shape main.ts uses. Getting here took two wrong guesses at a MakeCode
    // "!!proc || !bin.finalPass" error that points at the line below and says
    // nothing useful; what actually broke the build was a syntax error further
    // down. This shape is kept because it matches the firmware that is known
    // to compile, NOT because early returns are proven to cause that error.
    if (cmd == "GETCFG") {
        cfgWanted = true
    }
%(RAW)s    else if (cmd.indexOf("SET ") == 0) {
        let parts = cmd.substr(4).split(" ")
        let id = parts[0]
        let val = parts.length > 1 ? parts[1] : ""
%(SETS)s    }
})

basic.forever(function () {
    if (cfgWanted) {
        cfgWanted = false
        cfgTxPos = 0
        cfgTxActive = true
        bluetooth.uartWriteLine("CFGBEGIN")
        cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
    }

    if (cfgTxActive && input.runningTime() >= cfgTxNextAt) {
        if (cfgTxPos < CFG.length) {
            bluetooth.uartWriteLine("CFG " + CFG.substr(cfgTxPos, 18))
            cfgTxPos += 18
            cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
        } else {
            bluetooth.uartWriteLine("CFGEND")
%(ONCFGEND)s            cfgTxActive = false
        }
    }

%(POLLBODY)s    basic.pause(5)
})

bluetooth.onBluetoothConnected(function () {
%(CONNECT)s})

bluetooth.onBluetoothDisconnected(function () {
%(DISCONNECT)s})
%(BOOT)s'''

T = {}

T["ble"] = dict(
    TITLE="THE LINK ITSELF", EXT="bluetooth", TWIN="test-ble.ts",
    PANEL="LINK", THING="radio", POLL=1000,
    PASS="the uptime counts up on its own, and Beep makes a sound when pressed.",
    MATRIX="", RAW="",
    HELPERS='''const FIRMWARE_VERSION = "test-link"
let lastSec = -1

''',
    SETS='''        if (id == "btn_buzz" && val == "1") {
            music.playTone(988, music.beat(BeatFraction.Sixteenth))
        }
''',
    ONCFGEND='            bluetooth.uartWriteLine("UPD lbl_ver " + FIRMWARE_VERSION)\n',
    POLLBODY='''    if (input.runningTime() >= nextPollAt) {
        nextPollAt = input.runningTime() + POLL_MS
        // Proves the outbound direction unaided: if this number climbs on the
        // panel, the robot is talking and nothing else needs to be believed.
        let sec = Math.idiv(input.runningTime(), 1000)
        if (sec != lastSec) {
            lastSec = sec
            bluetooth.uartWriteLine("UPD lbl_heartbeat " + sec + "s")
        }
    }

''',
    CONNECT="    basic.showIcon(IconNames.Yes)\n",
    DISCONNECT="    basic.showIcon(IconNames.No)\n",
    BOOT='\nbasic.showString("BLE")\n')

T["leds"] = dict(
    TITLE="HEADLIGHTS", EXT="mecanum_robot_v2, bluetooth", TWIN="test-leds.ts",
    PANEL="HEADLIGHTS", THING="lamp", POLL=0,
    PASS="each switch turns its lamp on and off.",
    MATRIX="", RAW="", HELPERS="",
    SETS='''        if (id == "toggle_led_l") {
            mecanumRobotV2.setLed(LedCount.Left, val == "1" ? LedState.ON : LedState.OFF)
        }
        else if (id == "toggle_led_r") {
            mecanumRobotV2.setLed(LedCount.Right, val == "1" ? LedState.ON : LedState.OFF)
        }
''',
    ONCFGEND="", POLLBODY="",
    CONNECT="    basic.showIcon(IconNames.Yes)\n",
    DISCONNECT='''    mecanumRobotV2.setLed(LedCount.Left, LedState.OFF)
    mecanumRobotV2.setLed(LedCount.Right, LedState.OFF)
    basic.showIcon(IconNames.No)
''',
    BOOT='\nbasic.showString("LED")\n')

T["motors"] = dict(
    TITLE="MOTORS", EXT="mecanum_robot_v2, bluetooth", TWIN="test-motors.ts",
    PANEL="MOTORS", THING="motor", POLL=0,
    PASS="each arrow moves the robot that way, the corners strafe diagonally,\n *       STOP halts it, and Speed changes how fast.",
    MATRIX="",
    RAW='''    else if (cmd.length == 1 && cmd.charCodeAt(0) >= 97 && cmd.charCodeAt(0) <= 112) {
        handleDpadMask(cmd.charCodeAt(0) - 97)
    }
''',
    HELPERS='''let driveSpeed = 78

function drive(wheel: LR, value: number) {
    mecanumRobotV2.Motor(wheel, value >= 0 ? MD.Forward : MD.Back, Math.abs(value))
}

// Mecanum mixing, NOT tank mixing. Each wheel gets its own sign, which is what
// lets the chassis strafe sideways instead of just turning. The signs match
// test-motors.ts, where strafe left is -1, 1, 1, -1 and strafe right is the
// mirror of it; feeding both left wheels the same value would spin the robot
// on the spot and the diagonal buttons would do nothing useful.
function runMecanum(nx: number, ny: number) {
    let a = Math.constrain((ny + nx) * driveSpeed, -driveSpeed, driveSpeed)
    let b = Math.constrain((ny - nx) * driveSpeed, -driveSpeed, driveSpeed)
    drive(LR.Upper_left, a)
    drive(LR.Lower_left, b)
    drive(LR.Upper_right, b)
    drive(LR.Lower_right, a)
}

// The app sends the COMPLETE 4-bit button state as one byte 'a'..'p', so a
// dropped packet is corrected by the next one instead of leaving a direction
// stuck on. Same wire format as main.ts.
function handleDpadMask(mask: number) {
    let ny = 0
    let nx = 0
    if ((mask & 1) != 0) {
        ny += 1
    }
    if ((mask & 2) != 0) {
        ny -= 1
    }
    if ((mask & 4) != 0) {
        nx -= 1
    }
    if ((mask & 8) != 0) {
        nx += 1
    }
    if (nx == 0 && ny == 0) {
        mecanumRobotV2.state()
        return
    }
    runMecanum(nx, ny)
}

''',
    SETS='''        if (id == "btn_stop" && val == "1") {
            mecanumRobotV2.state()
        }
        else if (id == "spd") {
            driveSpeed = Math.constrain(parseInt(val), 24, 100)
            bluetooth.uartWriteLine("UPD gauge_spd " + driveSpeed)
        }
        else if (id == "dpad_move") {
            // Text form, for the stock bit-rxy app which sends no mask byte.
            let pressed = parts.length > 2 && parts[2] == "1"
            let mask = 0
            if (val == "up" && pressed) {
                mask = 1
            }
            else if (val == "down" && pressed) {
                mask = 2
            }
            else if (val == "left" && pressed) {
                mask = 4
            }
            else if (val == "right" && pressed) {
                mask = 8
            }
            handleDpadMask(mask)
        }
''',
    ONCFGEND='            bluetooth.uartWriteLine("UPD gauge_spd " + driveSpeed)\n',
    POLLBODY="",
    CONNECT="    basic.showIcon(IconNames.Yes)\n",
    DISCONNECT="    mecanumRobotV2.state()\n    basic.showIcon(IconNames.No)\n",
    BOOT='\nbasic.showString("MOT")\n')

T["servo"] = dict(
    TITLE="HEAD SERVO", EXT="mecanum_robot_v2, bluetooth", TWIN="test-servo.ts",
    PANEL="HEAD", THING="servo", POLL=0,
    PASS="the head turns to match the slider, and the gauge follows it.",
    MATRIX="", RAW="",
    HELPERS='''// test-servo.ts found this chassis needs mechanical trim: 90 alone does not
// point straight ahead. Tune here, then copy the value into main.ts.
const SERVO_OFFSET = 20

function head(angle: number) {
    let a = Math.constrain(angle + SERVO_OFFSET, 0, 180)
    mecanumRobotV2.setServo(a)
}

''',
    SETS='''        if (id == "slider_srv1") {
            let angle = Math.constrain(parseInt(val), 0, 180)
            head(angle)
            bluetooth.uartWriteLine("UPD gauge_srv1 " + angle)
        }
''',
    ONCFGEND='            bluetooth.uartWriteLine("UPD gauge_srv1 90")\n',
    POLLBODY="",
    CONNECT="    basic.showIcon(IconNames.Yes)\n",
    DISCONNECT="    basic.showIcon(IconNames.No)\n",
    BOOT='\nhead(90)\nbasic.showString("SRV")\n')

T["distance"] = dict(
    TITLE="ULTRASONIC", EXT="mecanum_robot_v2, bluetooth", TWIN="test-ultrasonic.ts",
    PANEL="DISTANCE", THING="sensor", POLL=300,
    PASS="the number and the graph follow your hand, and Obstacle pops up close in.",
    MATRIX="", RAW="",
    HELPERS='''// main.ts warns that ultra() BUSY-WAITS: a missing echo costs ~250ms and
// freezes the whole runtime, not just this loop. Polling slowly is deliberate.
let lastAlertAt = 0

''',
    SETS="", ONCFGEND="",
    POLLBODY='''    if (input.runningTime() >= nextPollAt) {
        nextPollAt = input.runningTime() + POLL_MS
        let d = mecanumRobotV2.ultra()
        if (d > 0) {
            bluetooth.uartWriteLine("UPD gauge_dist " + d)
            bluetooth.uartWriteLine("UPD graph_dist " + d)
            // Edge-triggered with a cool-down: the app raises a toast per
            // message, so repeating it every poll would bury the screen.
            if (d < 20 && input.runningTime() - lastAlertAt > 3000) {
                lastAlertAt = input.runningTime()
                bluetooth.uartWriteLine("UPD alert Obstacle " + d + "cm")
            }
        }
    }

''',
    CONNECT="    basic.showIcon(IconNames.Yes)\n",
    DISCONNECT="    basic.showIcon(IconNames.No)\n",
    BOOT='\nbasic.showString("DST")\n')

T["line"] = dict(
    TITLE="LINE SENSORS", EXT="mecanum_robot_v2, bluetooth", TWIN="test-line.ts",
    PANEL="LINE SENSORS", THING="sensor", POLL=150,
    PASS="each light changes as black tape passes under that sensor.",
    MATRIX='''
// P3, P4 and P10 are LED-matrix pins. The display MUST be off or the sensors
// read nonsense -- the same constraint the real firmware lives with. Feedback
// therefore goes to the left headlight, not the screen.
led.enable(false)
''',
    RAW="",
    HELPERS="let lastL = -1\nlet lastC = -1\nlet lastR = -1\n\n",
    SETS="", ONCFGEND="",
    POLLBODY='''    if (input.runningTime() >= nextPollAt) {
        nextPollAt = input.runningTime() + POLL_MS
        let l = mecanumRobotV2.LineTracking(LT.Left)
        let c = mecanumRobotV2.LineTracking(LT.Center)
        let r = mecanumRobotV2.LineTracking(LT.Right)
        // On change only: these sit still most of the time.
        if (l != lastL) {
            lastL = l
            bluetooth.uartWriteLine("UPD ln_l " + l)
        }
        if (c != lastC) {
            lastC = c
            bluetooth.uartWriteLine("UPD ln_c " + c)
        }
        if (r != lastR) {
            lastR = r
            bluetooth.uartWriteLine("UPD ln_r " + r)
        }
    }

''',
    CONNECT="    mecanumRobotV2.setLed(LedCount.Left, LedState.ON)\n",
    DISCONNECT="    mecanumRobotV2.setLed(LedCount.Left, LedState.OFF)\n",
    BOOT="")

T["lights"] = dict(
    TITLE="NEOPIXEL STRIP", EXT="mecanum_robot_v2, neopixel, bluetooth",
    TWIN="test-neopixel.ts", PANEL="LIGHTS", THING="strip", POLL=0,
    PASS="both lamps switch, and the strip changes colour and brightness.",
    MATRIX='''
// P7 (the strip) is an LED-matrix pin, so the display must be off. Feedback
// goes to the left headlight instead.
led.enable(false)
''',
    RAW="",
    HELPERS='''const NEOPIXEL_PIN = DigitalPin.P7
const NEOPIXEL_COUNT = 4
let strip = neopixel.create(NEOPIXEL_PIN, NEOPIXEL_COUNT, NeoPixelMode.RGB)
let npOn = false
let npBright = 150
let npColour = neopixel.colors(NeoPixelColors.Red)

function paint() {
    strip.setBrightness(npBright)
    if (npOn) {
        strip.showColor(npColour)
    } else {
        strip.clear()
        strip.show()
    }
}

''',
    SETS='''        if (id == "toggle_led_l") {
            mecanumRobotV2.setLed(LedCount.Left, val == "1" ? LedState.ON : LedState.OFF)
        }
        else if (id == "toggle_led_r") {
            mecanumRobotV2.setLed(LedCount.Right, val == "1" ? LedState.ON : LedState.OFF)
        }
        else if (id == "toggle_np") {
            npOn = val == "1"
            paint()
        }
        else if (id == "np_bright") {
            npBright = Math.constrain(parseInt(val), 0, 255)
            paint()
        }
        else if (id == "np_color") {
            // The app sends the option TEXT, so match names, not an index.
            if (val == "Red") {
                npColour = neopixel.colors(NeoPixelColors.Red)
            } else if (val == "Orange") {
                npColour = neopixel.colors(NeoPixelColors.Orange)
            } else if (val == "Yellow") {
                npColour = neopixel.colors(NeoPixelColors.Yellow)
            } else if (val == "Green") {
                npColour = neopixel.colors(NeoPixelColors.Green)
            } else if (val == "Blue") {
                npColour = neopixel.colors(NeoPixelColors.Blue)
            } else if (val == "Indigo") {
                npColour = neopixel.colors(NeoPixelColors.Indigo)
            } else if (val == "Violet") {
                npColour = neopixel.colors(NeoPixelColors.Violet)
            } else if (val == "Purple") {
                npColour = neopixel.colors(NeoPixelColors.Purple)
            } else {
                npColour = neopixel.colors(NeoPixelColors.White)
            }
            paint()
        }
''',
    ONCFGEND="", POLLBODY="",
    CONNECT="    mecanumRobotV2.setLed(LedCount.Left, LedState.ON)\n",
    DISCONNECT="    mecanumRobotV2.setLed(LedCount.Left, LedState.OFF)\n",
    BOOT="\npaint()\n")

T["microbit"] = dict(
    TITLE="MICRO:BIT SENSORS", EXT="bluetooth, microphone", TWIN="test-microbit.ts",
    PANEL="MICRO:BIT", THING="sensor", POLL=400,
    PASS="clapping moves Sound, tilting moves Tilt X/Y, and A/B/logo light up.",
    MATRIX="", RAW="",
    HELPERS="let lastA = -1\nlet lastB = -1\nlet lastLogo = -1\n\n",
    SETS="", ONCFGEND="",
    POLLBODY='''    if (input.runningTime() >= nextPollAt) {
        nextPollAt = input.runningTime() + POLL_MS
        bluetooth.uartWriteLine("UPD gauge_sound " + input.soundLevel())
        bluetooth.uartWriteLine("UPD gauge_temp " + input.temperature())
        bluetooth.uartWriteLine("UPD gauge_tiltx " +
            Math.constrain(Math.idiv(input.acceleration(Dimension.X), 10), -100, 100))
        bluetooth.uartWriteLine("UPD gauge_tilty " +
            Math.constrain(Math.idiv(input.acceleration(Dimension.Y), 10), -100, 100))

        let a = input.buttonIsPressed(Button.A) ? 1 : 0
        let b = input.buttonIsPressed(Button.B) ? 1 : 0
        let lg = input.logoIsPressed() ? 1 : 0
        if (a != lastA) {
            lastA = a
            bluetooth.uartWriteLine("UPD led_btn_a " + a)
        }
        if (b != lastB) {
            lastB = b
            bluetooth.uartWriteLine("UPD led_btn_b " + b)
        }
        if (lg != lastLogo) {
            lastLogo = lg
            bluetooth.uartWriteLine("UPD led_logo " + lg)
        }
    }

''',
    CONNECT="    basic.showIcon(IconNames.Yes)\n",
    DISCONNECT="    basic.showIcon(IconNames.No)\n",
    BOOT='\nbasic.showString("MB")\n')

ORDER = ["ble", "leds", "motors", "servo", "distance", "line", "lights", "microbit"]
for name in ORDER:
    d = dict(T[name])
    d["CFG"] = B64[name]
    out = SKEL % d
    fn = f"{HERE}/test-app-{name}.ts"
    open(fn, "w", encoding="utf-8", newline="\n").write(out)
    bad = re.findall(r"\{ *[^}\n]*; *return *\}", out)
    print(f"  test-app-{name+'.ts':16} {len(out.splitlines()):4} lines  "
          f"CFG {len(d['CFG']):5}  parser-trap: {'FAIL' if bad else 'none'}")
print(f"\nwrote {len(ORDER)} app-driven tests")
