/**
 * TEST: MOTORS, DRIVEN FROM THE APP - flash this alone.
 *
 * Extensions: mecanum_robot_v2, bluetooth
 *
 * The app-driven twin of test-motors.ts. That one runs a fixed sequence while you
 * watch; this one hands the subsystem to a child through the phone.
 *
 * Open the app, press Connect, and the MOTORS panel appears by itself. The
 * layout lives in this file and is sent over the link -- nothing to import.
 *
 * PASS: each arrow moves the robot that way, the corners strafe diagonally,
 *       STOP halts it, and Speed changes how fast.
 * FAIL: panel never appears -> run test-app-ble.ts first. That is a link
 *                             fault, not a motor fault.
 *       panel appears but nothing happens -> run test-motors.ts, which removes
 *                             Bluetooth from the picture entirely.
 */

// Generated by tests/gen_test_layouts.py. Widget ids match main.ts on purpose,
// so the handlers below are the real ones rather than lookalikes.
const CFG = "eyJ0aXRsZSI6Ik1lY2FudW0gLSBNb3RvcnMgdGVzdCIsIndpZGdldHMiOlt7ImlkIjoiZ3JwX3Rlc3QiLCJ0IjoiZ3JvdXAiLCJsYWJlbCI6Ik1PVE9SUyIsImNvbG9yIjoiIzAwZDRmZiIsIngiOjU2LCJ5Ijo0MiwidyI6NjU4LCJoIjo3NDIsImNoaWxkcmVuIjpbImRwYWRfbW92ZSIsInNwZCIsImJ0bl9zdG9wIiwiZ2F1Z2Vfc3BkIl19LHsiaWQiOiJkcGFkX21vdmUiLCJ0IjoiZHBhZCIsIngiOjgwLCJ5IjoxMDAsInciOjQyMCwiaCI6NDIwLCJsYWJlbCI6Ik1lY2FudW0gZHJpdmUiLCJtb2RlbCI6Im1lY2FudW0iLCJncm91cElkIjoiZ3JwX3Rlc3QifSx7ImlkIjoic3BkIiwidCI6InNsaWRlciIsIngiOjU0MCwieSI6MTAwLCJ3IjoxNTAsImgiOjI0MCwibGFiZWwiOiJTcGVlZCIsIm1pbiI6MjQsIm1heCI6MTAwLCJzdGVwIjoyLCJ2YWx1ZSI6NzgsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJidG5fc3RvcCIsInQiOiJidXR0b24iLCJ4Ijo1NDAsInkiOjM4MCwidyI6MTUwLCJoIjoxNDAsImxhYmVsIjoiU1RPUCIsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJnYXVnZV9zcGQiLCJ0IjoiZ2F1Z2UiLCJ4Ijo4MCwieSI6NTYwLCJ3IjoyMjAsImgiOjIwMCwibGFiZWwiOiJNb3RvciBzcGVlZCIsIm1pbiI6MjQsIm1heCI6MTAwLCJkZWNpbWFscyI6MCwibW9kZWwiOiJtaW4iLCJzb3VyY2UiOiJzcGQiLCJ2YWx1ZSI6NzgsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJsYmxfaGludCIsInQiOiJsYWJlbCIsIngiOjgwLCJ5Ijo4MDAsInciOjYxMCwiaCI6NzAsImxhYmVsIjoiUHJlc3MgYW4gYXJyb3cuIFRoZSByb2JvdCBtb3ZlcyB0aGF0IHdheS4gVGhlIGNvcm5lcnMgZ28gZGlhZ29uYWxseS4iLCJ2YWx1ZSI6IlByZXNzIGFuIGFycm93LiBUaGUgcm9ib3QgbW92ZXMgdGhhdCB3YXkuIFRoZSBjb3JuZXJzIGdvIGRpYWdvbmFsbHkuIiwibW9kZWwiOiJjYXJkIn1dLCJjYW52YXMiOnsidyI6NzcwLCJoIjo5MjZ9fQ=="

bluetooth.startUartService()
bluetooth.setTransmitPower(7)

let cfgWanted = false
let cfgTxPos = 0
let cfgTxActive = false
let cfgTxNextAt = 0
let nextPollAt = 0
const CFG_TX_GAP_MS = 35
const POLL_MS = 0

let driveSpeed = 78

function drive(wheel: LR, value: number) {
    mecanumRobotV2.Motor(wheel, value >= 0 ? MD.Forward : MD.Back, Math.abs(value))
}

// Mecanum mixing, NOT tank mixing. Each wheel gets its own sign, which is what
// lets the chassis strafe sideways instead of just turning. The signs match
// test-motors.ts, where strafe left is -1, 1, 1, -1 and strafe right is the
// mirror of it; feeding both left wheels the same value would spin the robot
// on the spot and the diagonal buttons would do nothing useful.
function runMecanum(nx: number, ny: number) {
    let a = Math.constrain((ny + nx) * driveSpeed, -driveSpeed, driveSpeed)
    let b = Math.constrain((ny - nx) * driveSpeed, -driveSpeed, driveSpeed)
    drive(LR.Upper_left, a)
    drive(LR.Lower_left, b)
    drive(LR.Upper_right, b)
    drive(LR.Lower_right, a)
}

// The app sends the COMPLETE 4-bit button state as one byte 'a'..'p', so a
// dropped packet is corrected by the next one instead of leaving a direction
// stuck on. Same wire format as main.ts.
function handleDpadMask(mask: number) {
    let ny = 0
    let nx = 0
    if ((mask & 1) != 0) {
        ny += 1
    }
    if ((mask & 2) != 0) {
        ny -= 1
    }
    if ((mask & 4) != 0) {
        nx -= 1
    }
    if ((mask & 8) != 0) {
        nx += 1
    }
    if (nx == 0 && ny == 0) {
        mecanumRobotV2.state()
        return
    }
    runMecanum(nx, ny)
}

// Only ever sets flags and drives hardware. The CFG burst is NOT sent from
// here -- see the forever loop below.
bluetooth.onUartDataReceived(serial.delimiters(Delimiters.NewLine), function () {
    let cmd = bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine))
    // Chained if/else-if with no `return` inside this lambda, matching the
    // shape main.ts uses. Getting here took two wrong guesses at a MakeCode
    // "!!proc || !bin.finalPass" error that points at the line below and says
    // nothing useful; what actually broke the build was a syntax error further
    // down. This shape is kept because it matches the firmware that is known
    // to compile, NOT because early returns are proven to cause that error.
    if (cmd == "GETCFG") {
        cfgWanted = true
    }
    else if (cmd.length == 1 && cmd.charCodeAt(0) >= 97 && cmd.charCodeAt(0) <= 112) {
        handleDpadMask(cmd.charCodeAt(0) - 97)
    }
    else if (cmd.indexOf("SET ") == 0) {
        let parts = cmd.substr(4).split(" ")
        let id = parts[0]
        let val = parts.length > 1 ? parts[1] : ""
        if (id == "btn_stop" && val == "1") {
            mecanumRobotV2.state()
        }
        else if (id == "spd") {
            driveSpeed = Math.constrain(parseInt(val), 24, 100)
            bluetooth.uartWriteLine("UPD gauge_spd " + driveSpeed)
        }
        else if (id == "dpad_move") {
            // Text form, for the stock bit-rxy app which sends no mask byte.
            let pressed = parts.length > 2 && parts[2] == "1"
            let mask = 0
            if (val == "up" && pressed) {
                mask = 1
            }
            else if (val == "down" && pressed) {
                mask = 2
            }
            else if (val == "left" && pressed) {
                mask = 4
            }
            else if (val == "right" && pressed) {
                mask = 8
            }
            handleDpadMask(mask)
        }
    }
})

basic.forever(function () {
    if (cfgWanted) {
        cfgWanted = false
        cfgTxPos = 0
        cfgTxActive = true
        bluetooth.uartWriteLine("CFGBEGIN")
        cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
    }

    if (cfgTxActive && input.runningTime() >= cfgTxNextAt) {
        if (cfgTxPos < CFG.length) {
            bluetooth.uartWriteLine("CFG " + CFG.substr(cfgTxPos, 18))
            cfgTxPos += 18
            cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
        } else {
            bluetooth.uartWriteLine("CFGEND")
            bluetooth.uartWriteLine("UPD gauge_spd " + driveSpeed)
            cfgTxActive = false
        }
    }

    basic.pause(5)
})

bluetooth.onBluetoothConnected(function () {
    basic.showIcon(IconNames.Yes)
})

bluetooth.onBluetoothDisconnected(function () {
    mecanumRobotV2.state()
    basic.showIcon(IconNames.No)
})

basic.showString("MOT")
