/**
 * TEST: NEOPIXEL STRIP, DRIVEN FROM THE APP - flash this alone.
 *
 * Extensions: mecanum_robot_v2, neopixel, bluetooth
 *
 * The app-driven twin of test-neopixel.ts. That one runs a fixed sequence while you
 * watch; this one hands the subsystem to a child through the phone.
 *
 * Open the app, press Connect, and the LIGHTS panel appears by itself. The
 * layout lives in this file and is sent over the link -- nothing to import.
 *
 * PASS: both lamps switch, and the strip changes colour and brightness.
 * FAIL: panel never appears -> run test-app-ble.ts first. That is a link
 *                             fault, not a strip fault.
 *       panel appears but nothing happens -> run test-neopixel.ts, which removes
 *                             Bluetooth from the picture entirely.
 */

// Generated by tests/gen_test_layouts.py. Widget ids match main.ts on purpose,
// so the handlers below are the real ones rather than lookalikes.
const CFG = "eyJ0aXRsZSI6Ik1lY2FudW0gLSBTdHJpcCB0ZXN0Iiwid2lkZ2V0cyI6W3siaWQiOiJncnBfdGVzdCIsInQiOiJncm91cCIsImxhYmVsIjoiTElHSFRTIiwiY29sb3IiOiIjYzA4NGZjIiwieCI6NTYsInkiOjQyLCJ3Ijo2MjgsImgiOjQ2MiwiY2hpbGRyZW4iOlsidG9nZ2xlX2xlZF9sIiwidG9nZ2xlX2xlZF9yIiwidG9nZ2xlX25wIiwibnBfY29sb3IiLCJucF9lZmZlY3QiLCJucF9icmlnaHQiXX0seyJpZCI6InRvZ2dsZV9sZWRfbCIsInQiOiJ0b2dnbGUiLCJ4Ijo4MCwieSI6MTAwLCJ3IjoxNDAsImgiOjEyMCwibGFiZWwiOiJMZWZ0IGxhbXAiLCJncm91cElkIjoiZ3JwX3Rlc3QifSx7ImlkIjoidG9nZ2xlX2xlZF9yIiwidCI6InRvZ2dsZSIsIngiOjI0MCwieSI6MTAwLCJ3IjoxNDAsImgiOjEyMCwibGFiZWwiOiJSaWdodCBsYW1wIiwiZ3JvdXBJZCI6ImdycF90ZXN0In0seyJpZCI6InRvZ2dsZV9ucCIsInQiOiJ0b2dnbGUiLCJ4Ijo0MDAsInkiOjEwMCwidyI6MTQwLCJoIjoxMjAsImxhYmVsIjoiU3RyaXAiLCJncm91cElkIjoiZ3JwX3Rlc3QifSx7ImlkIjoibnBfY29sb3IiLCJ0Ijoic2VsZWN0IiwieCI6ODAsInkiOjI2MCwidyI6MTkwLCJoIjo5MCwibGFiZWwiOiJDb2xvdXIiLCJvcHRpb25zIjoiUmVkLE9yYW5nZSxZZWxsb3csR3JlZW4sQmx1ZSxJbmRpZ28sVmlvbGV0LFB1cnBsZSxXaGl0ZSIsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJucF9lZmZlY3QiLCJ0Ijoic2VsZWN0IiwieCI6MjkwLCJ5IjoyNjAsInciOjE5MCwiaCI6OTAsImxhYmVsIjoiRWZmZWN0Iiwib3B0aW9ucyI6IlNvbGlkLFJhaW5ib3csQ2hhc2UsU3BhcmtsZSIsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJucF9icmlnaHQiLCJ0Ijoic2xpZGVyIiwieCI6NTEwLCJ5IjoyNDAsInciOjE1MCwiaCI6MjQwLCJsYWJlbCI6IkJyaWdodCIsIm1pbiI6MCwibWF4IjoyNTUsInN0ZXAiOjUsInZhbHVlIjoxNTAsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJsYmxfaGludCIsInQiOiJsYWJlbCIsIngiOjgwLCJ5Ijo1MjAsInciOjU4MCwiaCI6NzAsImxhYmVsIjoiU3dpdGNoIHRoZSBsYW1wcyBvbiwgdGhlbiBwaWNrIGEgY29sb3VyIGZvciB0aGUgc3RyaXAuIiwidmFsdWUiOiJTd2l0Y2ggdGhlIGxhbXBzIG9uLCB0aGVuIHBpY2sgYSBjb2xvdXIgZm9yIHRoZSBzdHJpcC4iLCJtb2RlbCI6ImNhcmQifV0sImNhbnZhcyI6eyJ3Ijo3NDAsImgiOjY0Nn19"

bluetooth.startUartService()
bluetooth.setTransmitPower(7)

// P7 (the strip) is an LED-matrix pin, so the display must be off. Feedback
// goes to the left headlight instead.
led.enable(false)

let cfgWanted = false
let cfgTxPos = 0
let cfgTxActive = false
let cfgTxNextAt = 0
let nextPollAt = 0
const CFG_TX_GAP_MS = 35
const POLL_MS = 0

const NEOPIXEL_PIN = DigitalPin.P7
const NEOPIXEL_COUNT = 4
let strip = neopixel.create(NEOPIXEL_PIN, NEOPIXEL_COUNT, NeoPixelMode.RGB)
let npOn = false
let npBright = 150
let npColour = neopixel.colors(NeoPixelColors.Red)

function paint() {
    strip.setBrightness(npBright)
    if (npOn) {
        strip.showColor(npColour)
    } else {
        strip.clear()
        strip.show()
    }
}

// Only ever sets flags and drives hardware. The CFG burst is NOT sent from
// here -- see the forever loop below.
bluetooth.onUartDataReceived(serial.delimiters(Delimiters.NewLine), function () {
    let cmd = bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine))
    // Chained if/else-if with no `return` inside this lambda, matching the
    // shape main.ts uses. Getting here took two wrong guesses at a MakeCode
    // "!!proc || !bin.finalPass" error that points at the line below and says
    // nothing useful; what actually broke the build was a syntax error further
    // down. This shape is kept because it matches the firmware that is known
    // to compile, NOT because early returns are proven to cause that error.
    if (cmd == "GETCFG") {
        cfgWanted = true
    }
    else if (cmd.indexOf("SET ") == 0) {
        let parts = cmd.substr(4).split(" ")
        let id = parts[0]
        let val = parts.length > 1 ? parts[1] : ""
        if (id == "toggle_led_l") {
            mecanumRobotV2.setLed(LedCount.Left, val == "1" ? LedState.ON : LedState.OFF)
        }
        else if (id == "toggle_led_r") {
            mecanumRobotV2.setLed(LedCount.Right, val == "1" ? LedState.ON : LedState.OFF)
        }
        else if (id == "toggle_np") {
            npOn = val == "1"
            paint()
        }
        else if (id == "np_bright") {
            npBright = Math.constrain(parseInt(val), 0, 255)
            paint()
        }
        else if (id == "np_color") {
            // The app sends the option TEXT, so match names, not an index.
            if (val == "Red") {
                npColour = neopixel.colors(NeoPixelColors.Red)
            } else if (val == "Orange") {
                npColour = neopixel.colors(NeoPixelColors.Orange)
            } else if (val == "Yellow") {
                npColour = neopixel.colors(NeoPixelColors.Yellow)
            } else if (val == "Green") {
                npColour = neopixel.colors(NeoPixelColors.Green)
            } else if (val == "Blue") {
                npColour = neopixel.colors(NeoPixelColors.Blue)
            } else if (val == "Indigo") {
                npColour = neopixel.colors(NeoPixelColors.Indigo)
            } else if (val == "Violet") {
                npColour = neopixel.colors(NeoPixelColors.Violet)
            } else if (val == "Purple") {
                npColour = neopixel.colors(NeoPixelColors.Purple)
            } else {
                npColour = neopixel.colors(NeoPixelColors.White)
            }
            paint()
        }
    }
})

basic.forever(function () {
    if (cfgWanted) {
        cfgWanted = false
        cfgTxPos = 0
        cfgTxActive = true
        bluetooth.uartWriteLine("CFGBEGIN")
        cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
    }

    if (cfgTxActive && input.runningTime() >= cfgTxNextAt) {
        if (cfgTxPos < CFG.length) {
            bluetooth.uartWriteLine("CFG " + CFG.substr(cfgTxPos, 18))
            cfgTxPos += 18
            cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
        } else {
            bluetooth.uartWriteLine("CFGEND")
            cfgTxActive = false
        }
    }

    basic.pause(5)
})

bluetooth.onBluetoothConnected(function () {
    mecanumRobotV2.setLed(LedCount.Left, LedState.ON)
})

bluetooth.onBluetoothDisconnected(function () {
    mecanumRobotV2.setLed(LedCount.Left, LedState.OFF)
})

paint()
