/**
 * TEST: HEAD SERVO, DRIVEN FROM THE APP - flash this alone.
 *
 * Extensions: mecanum_robot_v2, bluetooth
 *
 * The app-driven twin of test-servo.ts. That one runs a fixed sequence while you
 * watch; this one hands the subsystem to a child through the phone.
 *
 * Open the app, press Connect, and the HEAD panel appears by itself. The
 * layout lives in this file and is sent over the link -- nothing to import.
 *
 * PASS: the head turns to match the slider, and the gauge follows it.
 * FAIL: panel never appears -> run test-app-ble.ts first. That is a link
 *                             fault, not a servo fault.
 *       panel appears but nothing happens -> run test-servo.ts, which removes
 *                             Bluetooth from the picture entirely.
 */

// Generated by tests/gen_test_layouts.py. Widget ids match main.ts on purpose,
// so the handlers below are the real ones rather than lookalikes.
const CFG = "eyJ0aXRsZSI6Ik1lY2FudW0gLSBIZWFkIHRlc3QiLCJ3aWRnZXRzIjpbeyJpZCI6ImdycF90ZXN0IiwidCI6Imdyb3VwIiwibGFiZWwiOiJIRUFEIiwiY29sb3IiOiIjZmY5NTAwIiwieCI6NTYsInkiOjQyLCJ3Ijo0NTgsImgiOjM0MiwiY2hpbGRyZW4iOlsic2xpZGVyX3NydjEiLCJnYXVnZV9zcnYxIl19LHsiaWQiOiJzbGlkZXJfc3J2MSIsInQiOiJzbGlkZXIiLCJ4Ijo4MCwieSI6MTAwLCJ3IjoxNTAsImgiOjI2MCwibGFiZWwiOiJIZWFkIGFuZ2xlIiwibWluIjowLCJtYXgiOjE4MCwic3RlcCI6MSwidmFsdWUiOjkwLCJncm91cElkIjoiZ3JwX3Rlc3QifSx7ImlkIjoiZ2F1Z2Vfc3J2MSIsInQiOiJnYXVnZSIsIngiOjI3MCwieSI6MTAwLCJ3IjoyMjAsImgiOjIwMCwibGFiZWwiOiJBbmdsZSIsIm1pbiI6MCwibWF4IjoxODAsInVuaXRzIjoiZGVnIiwiZGVjaW1hbHMiOjAsIm1vZGVsIjoibWluIiwic291cmNlIjoic2xpZGVyX3NydjEiLCJ2YWx1ZSI6OTAsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJsYmxfaGludCIsInQiOiJsYWJlbCIsIngiOjgwLCJ5Ijo0MDAsInciOjQxMCwiaCI6NzAsImxhYmVsIjoiU2xpZGUgaXQuIFRoZSBzZW5zb3IgaGVhZCBzaG91bGQgdHVybiB0byBtYXRjaCB0aGUgbnVtYmVyLiIsInZhbHVlIjoiU2xpZGUgaXQuIFRoZSBzZW5zb3IgaGVhZCBzaG91bGQgdHVybiB0byBtYXRjaCB0aGUgbnVtYmVyLiIsIm1vZGVsIjoiY2FyZCJ9XSwiY2FudmFzIjp7InciOjU3MCwiaCI6NTI2fX0="

bluetooth.startUartService()
bluetooth.setTransmitPower(7)

let cfgWanted = false
let cfgTxPos = 0
let cfgTxActive = false
let cfgTxNextAt = 0
let nextPollAt = 0
const CFG_TX_GAP_MS = 35
const POLL_MS = 0

// test-servo.ts found this chassis needs mechanical trim: 90 alone does not
// point straight ahead. Tune here, then copy the value into main.ts.
const SERVO_OFFSET = 20

function head(angle: number) {
    let a = Math.constrain(angle + SERVO_OFFSET, 0, 180)
    mecanumRobotV2.setServo(a)
}

// Only ever sets flags and drives hardware. The CFG burst is NOT sent from
// here -- see the forever loop below.
bluetooth.onUartDataReceived(serial.delimiters(Delimiters.NewLine), function () {
    let cmd = bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine))
    // Chained if/else-if with no `return` inside this lambda, matching the
    // shape main.ts uses. Getting here took two wrong guesses at a MakeCode
    // "!!proc || !bin.finalPass" error that points at the line below and says
    // nothing useful; what actually broke the build was a syntax error further
    // down. This shape is kept because it matches the firmware that is known
    // to compile, NOT because early returns are proven to cause that error.
    if (cmd == "GETCFG") {
        cfgWanted = true
    }
    else if (cmd.indexOf("SET ") == 0) {
        let parts = cmd.substr(4).split(" ")
        let id = parts[0]
        let val = parts.length > 1 ? parts[1] : ""
        if (id == "slider_srv1") {
            let angle = Math.constrain(parseInt(val), 0, 180)
            head(angle)
            bluetooth.uartWriteLine("UPD gauge_srv1 " + angle)
        }
    }
})

basic.forever(function () {
    if (cfgWanted) {
        cfgWanted = false
        cfgTxPos = 0
        cfgTxActive = true
        bluetooth.uartWriteLine("CFGBEGIN")
        cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
    }

    if (cfgTxActive && input.runningTime() >= cfgTxNextAt) {
        if (cfgTxPos < CFG.length) {
            bluetooth.uartWriteLine("CFG " + CFG.substr(cfgTxPos, 18))
            cfgTxPos += 18
            cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
        } else {
            bluetooth.uartWriteLine("CFGEND")
            bluetooth.uartWriteLine("UPD gauge_srv1 90")
            cfgTxActive = false
        }
    }

    basic.pause(5)
})

bluetooth.onBluetoothConnected(function () {
    basic.showIcon(IconNames.Yes)
})

bluetooth.onBluetoothDisconnected(function () {
    basic.showIcon(IconNames.No)
})

head(90)
basic.showString("SRV")
