/**
 * TEST: THE LINK ITSELF, DRIVEN FROM THE APP - flash this alone.
 *
 * Extensions: bluetooth
 *
 * The app-driven twin of test-ble.ts. That one runs a fixed sequence while you
 * watch; this one hands the subsystem to a child through the phone.
 *
 * Open the app, press Connect, and the LINK panel appears by itself. The
 * layout lives in this file and is sent over the link -- nothing to import.
 *
 * PASS: the uptime counts up on its own, and Beep makes a sound when pressed.
 * FAIL: panel never appears -> run test-app-ble.ts first. That is a link
 *                             fault, not a radio fault.
 *       panel appears but nothing happens -> run test-ble.ts, which removes
 *                             Bluetooth from the picture entirely.
 */

// Generated by tests/gen_test_layouts.py. Widget ids match main.ts on purpose,
// so the handlers below are the real ones rather than lookalikes.
const CFG = "eyJ0aXRsZSI6Ik1lY2FudW0gLSBMaW5rIHRlc3QiLCJ3aWRnZXRzIjpbeyJpZCI6ImdycF90ZXN0IiwidCI6Imdyb3VwIiwibGFiZWwiOiJMSU5LIiwiY29sb3IiOiIjNjBhNWZhIiwieCI6NTYsInkiOjQyLCJ3Ijo1MzgsImgiOjI2MiwiY2hpbGRyZW4iOlsibGJsX3ZlciIsImxibF9oZWFydGJlYXQiLCJidG5fYnV6eiJdfSx7ImlkIjoibGJsX3ZlciIsInQiOiJsYWJlbCIsIngiOjgwLCJ5IjoxMDAsInciOjMwMCwiaCI6ODAsImxhYmVsIjoiRmlybXdhcmUiLCJtb2RlbCI6ImNhcmQiLCJncm91cElkIjoiZ3JwX3Rlc3QifSx7ImlkIjoibGJsX2hlYXJ0YmVhdCIsInQiOiJsYWJlbCIsIngiOjgwLCJ5IjoyMDAsInciOjMwMCwiaCI6ODAsImxhYmVsIjoiVXB0aW1lIiwibW9kZWwiOiJjYXJkIiwiZ3JvdXBJZCI6ImdycF90ZXN0In0seyJpZCI6ImJ0bl9idXp6IiwidCI6ImJ1dHRvbiIsIngiOjQyMCwieSI6MTAwLCJ3IjoxNTAsImgiOjE1MCwibGFiZWwiOiJCZWVwIiwiZ3JvdXBJZCI6ImdycF90ZXN0In0seyJpZCI6ImxibF9oaW50IiwidCI6ImxhYmVsIiwieCI6ODAsInkiOjMyMCwidyI6NDkwLCJoIjo3MCwibGFiZWwiOiJJZiB0aGUgdXB0aW1lIGNvdW50cyBhbmQgQmVlcCBtYWtlcyBhIHNvdW5kLCB0aGUgbGluayB3b3Jrcy4iLCJ2YWx1ZSI6IklmIHRoZSB1cHRpbWUgY291bnRzIGFuZCBCZWVwIG1ha2VzIGEgc291bmQsIHRoZSBsaW5rIHdvcmtzLiIsIm1vZGVsIjoiY2FyZCJ9XSwiY2FudmFzIjp7InciOjY1MCwiaCI6NDQ2fX0="

bluetooth.startUartService()
bluetooth.setTransmitPower(7)

let cfgWanted = false
let cfgTxPos = 0
let cfgTxActive = false
let cfgTxNextAt = 0
let nextPollAt = 0
const CFG_TX_GAP_MS = 35
const POLL_MS = 1000

const FIRMWARE_VERSION = "test-link"
let lastSec = -1

// Only ever sets flags and drives hardware. The CFG burst is NOT sent from
// here -- see the forever loop below.
bluetooth.onUartDataReceived(serial.delimiters(Delimiters.NewLine), function () {
    let cmd = bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine))
    // Chained if/else-if with no `return` inside this lambda, matching the
    // shape main.ts uses. Getting here took two wrong guesses at a MakeCode
    // "!!proc || !bin.finalPass" error that points at the line below and says
    // nothing useful; what actually broke the build was a syntax error further
    // down. This shape is kept because it matches the firmware that is known
    // to compile, NOT because early returns are proven to cause that error.
    if (cmd == "GETCFG") {
        cfgWanted = true
    }
    else if (cmd.indexOf("SET ") == 0) {
        let parts = cmd.substr(4).split(" ")
        let id = parts[0]
        let val = parts.length > 1 ? parts[1] : ""
        if (id == "btn_buzz" && val == "1") {
            music.playTone(988, music.beat(BeatFraction.Sixteenth))
        }
    }
})

basic.forever(function () {
    if (cfgWanted) {
        cfgWanted = false
        cfgTxPos = 0
        cfgTxActive = true
        bluetooth.uartWriteLine("CFGBEGIN")
        cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
    }

    if (cfgTxActive && input.runningTime() >= cfgTxNextAt) {
        if (cfgTxPos < CFG.length) {
            bluetooth.uartWriteLine("CFG " + CFG.substr(cfgTxPos, 18))
            cfgTxPos += 18
            cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
        } else {
            bluetooth.uartWriteLine("CFGEND")
            bluetooth.uartWriteLine("UPD lbl_ver " + FIRMWARE_VERSION)
            cfgTxActive = false
        }
    }

    if (input.runningTime() >= nextPollAt) {
        nextPollAt = input.runningTime() + POLL_MS
        // Proves the outbound direction unaided: if this number climbs on the
        // panel, the robot is talking and nothing else needs to be believed.
        let sec = Math.idiv(input.runningTime(), 1000)
        if (sec != lastSec) {
            lastSec = sec
            bluetooth.uartWriteLine("UPD lbl_heartbeat " + sec + "s")
        }
    }

    basic.pause(5)
})

bluetooth.onBluetoothConnected(function () {
    basic.showIcon(IconNames.Yes)
})

bluetooth.onBluetoothDisconnected(function () {
    basic.showIcon(IconNames.No)
})

basic.showString("BLE")
