/**
 * TEST: MICRO:BIT SENSORS, DRIVEN FROM THE APP - flash this alone.
 *
 * Extensions: bluetooth, microphone
 *
 * The app-driven twin of test-microbit.ts. That one runs a fixed sequence while you
 * watch; this one hands the subsystem to a child through the phone.
 *
 * Open the app, press Connect, and the MICRO:BIT panel appears by itself. The
 * layout lives in this file and is sent over the link -- nothing to import.
 *
 * PASS: clapping moves Sound, tilting moves Tilt X/Y, and A/B/logo light up.
 * FAIL: panel never appears -> run test-app-ble.ts first. That is a link
 *                             fault, not a sensor fault.
 *       panel appears but nothing happens -> run test-microbit.ts, which removes
 *                             Bluetooth from the picture entirely.
 */

// Generated by tests/gen_test_layouts.py. Widget ids match main.ts on purpose,
// so the handlers below are the real ones rather than lookalikes.
const CFG = "eyJ0aXRsZSI6Ik1lY2FudW0gLSBtaWNybzpiaXQgdGVzdCIsIndpZGdldHMiOlt7ImlkIjoiZ3JwX3Rlc3QiLCJ0IjoiZ3JvdXAiLCJsYWJlbCI6Ik1JQ1JPOkJJVCIsImNvbG9yIjoiI2Y0NzJiNiIsIngiOjU2LCJ5Ijo0MiwidyI6NjE4LCJoIjo1MDIsImNoaWxkcmVuIjpbImdhdWdlX3NvdW5kIiwiZ2F1Z2VfdGVtcCIsImdhdWdlX3RpbHR4IiwiZ2F1Z2VfdGlsdHkiLCJsZWRfYnRuX2EiLCJsZWRfYnRuX2IiLCJsZWRfbG9nbyJdfSx7ImlkIjoiZ2F1Z2Vfc291bmQiLCJ0IjoiZ2F1Z2UiLCJ4Ijo4MCwieSI6MTAwLCJ3IjoyMDAsImgiOjE5MCwibGFiZWwiOiJTb3VuZCIsIm1pbiI6MCwibWF4IjoyNTUsImRlY2ltYWxzIjowLCJncm91cElkIjoiZ3JwX3Rlc3QifSx7ImlkIjoiZ2F1Z2VfdGVtcCIsInQiOiJnYXVnZSIsIngiOjMwMCwieSI6MTAwLCJ3IjoyMDAsImgiOjE5MCwibGFiZWwiOiJUZW1wZXJhdHVyZSIsIm1pbiI6MCwibWF4Ijo1MCwidW5pdHMiOiJDIiwiZGVjaW1hbHMiOjAsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJnYXVnZV90aWx0eCIsInQiOiJnYXVnZSIsIngiOjgwLCJ5IjozMzAsInciOjIwMCwiaCI6MTkwLCJsYWJlbCI6IlRpbHQgWCIsIm1pbiI6LTEwMCwibWF4IjoxMDAsInVuaXRzIjoiJSIsImRlY2ltYWxzIjowLCJncm91cElkIjoiZ3JwX3Rlc3QifSx7ImlkIjoiZ2F1Z2VfdGlsdHkiLCJ0IjoiZ2F1Z2UiLCJ4IjozMDAsInkiOjMzMCwidyI6MjAwLCJoIjoxOTAsImxhYmVsIjoiVGlsdCBZIiwibWluIjotMTAwLCJtYXgiOjEwMCwidW5pdHMiOiIlIiwiZGVjaW1hbHMiOjAsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJsZWRfYnRuX2EiLCJ0IjoibGVkIiwieCI6NTQwLCJ5IjoxMTAsInciOjExMCwiaCI6MTIwLCJsYWJlbCI6IkJ1dHRvbiBBIiwibW9kZWwiOiJkb3QiLCJjb2xvck9uIjoiIzYwYTVmYSIsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJsZWRfYnRuX2IiLCJ0IjoibGVkIiwieCI6NTQwLCJ5IjoyNTAsInciOjExMCwiaCI6MTIwLCJsYWJlbCI6IkJ1dHRvbiBCIiwibW9kZWwiOiJkb3QiLCJjb2xvck9uIjoiIzYwYTVmYSIsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJsZWRfbG9nbyIsInQiOiJsZWQiLCJ4Ijo1NDAsInkiOjM5MCwidyI6MTEwLCJoIjoxMjAsImxhYmVsIjoiTG9nbyIsIm1vZGVsIjoiZG90IiwiY29sb3JPbiI6IiNmNDcyYjYiLCJncm91cElkIjoiZ3JwX3Rlc3QifSx7ImlkIjoibGJsX2hpbnQiLCJ0IjoibGFiZWwiLCJ4Ijo4MCwieSI6NTYwLCJ3Ijo1NzAsImgiOjcwLCJsYWJlbCI6IkNsYXAsIHRpbHQgdGhlIHJvYm90LCBwcmVzcyBBIGFuZCBCLiBFdmVyeXRoaW5nIHNob3VsZCBtb3ZlLiIsInZhbHVlIjoiQ2xhcCwgdGlsdCB0aGUgcm9ib3QsIHByZXNzIEEgYW5kIEIuIEV2ZXJ5dGhpbmcgc2hvdWxkIG1vdmUuIiwibW9kZWwiOiJjYXJkIn1dLCJjYW52YXMiOnsidyI6NzMwLCJoIjo2ODZ9fQ=="

bluetooth.startUartService()
bluetooth.setTransmitPower(7)

let cfgWanted = false
let cfgTxPos = 0
let cfgTxActive = false
let cfgTxNextAt = 0
let nextPollAt = 0
const CFG_TX_GAP_MS = 35
const POLL_MS = 400

let lastA = -1
let lastB = -1
let lastLogo = -1

// Only ever sets flags and drives hardware. The CFG burst is NOT sent from
// here -- see the forever loop below.
bluetooth.onUartDataReceived(serial.delimiters(Delimiters.NewLine), function () {
    let cmd = bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine))
    // Chained if/else-if with no `return` inside this lambda, matching the
    // shape main.ts uses. Getting here took two wrong guesses at a MakeCode
    // "!!proc || !bin.finalPass" error that points at the line below and says
    // nothing useful; what actually broke the build was a syntax error further
    // down. This shape is kept because it matches the firmware that is known
    // to compile, NOT because early returns are proven to cause that error.
    if (cmd == "GETCFG") {
        cfgWanted = true
    }
    else if (cmd.indexOf("SET ") == 0) {
        let parts = cmd.substr(4).split(" ")
        let id = parts[0]
        let val = parts.length > 1 ? parts[1] : ""
    }
})

basic.forever(function () {
    if (cfgWanted) {
        cfgWanted = false
        cfgTxPos = 0
        cfgTxActive = true
        bluetooth.uartWriteLine("CFGBEGIN")
        cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
    }

    if (cfgTxActive && input.runningTime() >= cfgTxNextAt) {
        if (cfgTxPos < CFG.length) {
            bluetooth.uartWriteLine("CFG " + CFG.substr(cfgTxPos, 18))
            cfgTxPos += 18
            cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
        } else {
            bluetooth.uartWriteLine("CFGEND")
            cfgTxActive = false
        }
    }

    if (input.runningTime() >= nextPollAt) {
        nextPollAt = input.runningTime() + POLL_MS
        bluetooth.uartWriteLine("UPD gauge_sound " + input.soundLevel())
        bluetooth.uartWriteLine("UPD gauge_temp " + input.temperature())
        bluetooth.uartWriteLine("UPD gauge_tiltx " +
            Math.constrain(Math.idiv(input.acceleration(Dimension.X), 10), -100, 100))
        bluetooth.uartWriteLine("UPD gauge_tilty " +
            Math.constrain(Math.idiv(input.acceleration(Dimension.Y), 10), -100, 100))

        let a = input.buttonIsPressed(Button.A) ? 1 : 0
        let b = input.buttonIsPressed(Button.B) ? 1 : 0
        let lg = input.logoIsPressed() ? 1 : 0
        if (a != lastA) {
            lastA = a
            bluetooth.uartWriteLine("UPD led_btn_a " + a)
        }
        if (b != lastB) {
            lastB = b
            bluetooth.uartWriteLine("UPD led_btn_b " + b)
        }
        if (lg != lastLogo) {
            lastLogo = lg
            bluetooth.uartWriteLine("UPD led_logo " + lg)
        }
    }

    basic.pause(5)
})

bluetooth.onBluetoothConnected(function () {
    basic.showIcon(IconNames.Yes)
})

bluetooth.onBluetoothDisconnected(function () {
    basic.showIcon(IconNames.No)
})

basic.showString("MB")
