/**
 * TEST: LINE SENSORS, DRIVEN FROM THE APP - flash this alone.
 *
 * Extensions: mecanum_robot_v2, bluetooth
 *
 * The app-driven twin of test-line.ts. That one runs a fixed sequence while you
 * watch; this one hands the subsystem to a child through the phone.
 *
 * Open the app, press Connect, and the LINE SENSORS panel appears by itself. The
 * layout lives in this file and is sent over the link -- nothing to import.
 *
 * PASS: each light changes as black tape passes under that sensor.
 * FAIL: panel never appears -> run test-app-ble.ts first. That is a link
 *                             fault, not a sensor fault.
 *       panel appears but nothing happens -> run test-line.ts, which removes
 *                             Bluetooth from the picture entirely.
 */

// Generated by tests/gen_test_layouts.py. Widget ids match main.ts on purpose,
// so the handlers below are the real ones rather than lookalikes.
const CFG = "eyJ0aXRsZSI6Ik1lY2FudW0gLSBMaW5lIHRlc3QiLCJ3aWRnZXRzIjpbeyJpZCI6ImdycF90ZXN0IiwidCI6Imdyb3VwIiwibGFiZWwiOiJMSU5FIFNFTlNPUlMiLCJjb2xvciI6IiMwMGU2NzYiLCJ4Ijo1NiwieSI6NDIsInciOjQ0OCwiaCI6MjEyLCJjaGlsZHJlbiI6WyJsbl9sIiwibG5fYyIsImxuX3IiXX0seyJpZCI6ImxuX2wiLCJ0IjoibGVkIiwieCI6ODAsInkiOjEwMCwidyI6MTIwLCJoIjoxMzAsImxhYmVsIjoiTGVmdCIsIm1vZGVsIjoiZG90IiwiY29sb3JPbiI6IiM0YWRlODAiLCJncm91cElkIjoiZ3JwX3Rlc3QifSx7ImlkIjoibG5fYyIsInQiOiJsZWQiLCJ4IjoyMjAsInkiOjEwMCwidyI6MTIwLCJoIjoxMzAsImxhYmVsIjoiQ2VudGVyIiwibW9kZWwiOiJkb3QiLCJjb2xvck9uIjoiIzRhZGU4MCIsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJsbl9yIiwidCI6ImxlZCIsIngiOjM2MCwieSI6MTAwLCJ3IjoxMjAsImgiOjEzMCwibGFiZWwiOiJSaWdodCIsIm1vZGVsIjoiZG90IiwiY29sb3JPbiI6IiM0YWRlODAiLCJncm91cElkIjoiZ3JwX3Rlc3QifSx7ImlkIjoibGJsX2hpbnQiLCJ0IjoibGFiZWwiLCJ4Ijo4MCwieSI6MjcwLCJ3Ijo0MDAsImgiOjcwLCJsYWJlbCI6IlNsaWRlIGJsYWNrIHRhcGUgdW5kZXIgdGhlIHJvYm90LiBUaGUgbGlnaHQgYWJvdmUgaXQgc2hvdWxkIGNoYW5nZS4iLCJ2YWx1ZSI6IlNsaWRlIGJsYWNrIHRhcGUgdW5kZXIgdGhlIHJvYm90LiBUaGUgbGlnaHQgYWJvdmUgaXQgc2hvdWxkIGNoYW5nZS4iLCJtb2RlbCI6ImNhcmQifV0sImNhbnZhcyI6eyJ3Ijo1NjAsImgiOjM5Nn19"

bluetooth.startUartService()
bluetooth.setTransmitPower(7)

// P3, P4 and P10 are LED-matrix pins. The display MUST be off or the sensors
// read nonsense -- the same constraint the real firmware lives with. Feedback
// therefore goes to the left headlight, not the screen.
led.enable(false)

let cfgWanted = false
let cfgTxPos = 0
let cfgTxActive = false
let cfgTxNextAt = 0
let nextPollAt = 0
const CFG_TX_GAP_MS = 35
const POLL_MS = 150

let lastL = -1
let lastC = -1
let lastR = -1

// Only ever sets flags and drives hardware. The CFG burst is NOT sent from
// here -- see the forever loop below.
bluetooth.onUartDataReceived(serial.delimiters(Delimiters.NewLine), function () {
    let cmd = bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine))
    // Chained if/else-if with no `return` inside this lambda, matching the
    // shape main.ts uses. Getting here took two wrong guesses at a MakeCode
    // "!!proc || !bin.finalPass" error that points at the line below and says
    // nothing useful; what actually broke the build was a syntax error further
    // down. This shape is kept because it matches the firmware that is known
    // to compile, NOT because early returns are proven to cause that error.
    if (cmd == "GETCFG") {
        cfgWanted = true
    }
    else if (cmd.indexOf("SET ") == 0) {
        let parts = cmd.substr(4).split(" ")
        let id = parts[0]
        let val = parts.length > 1 ? parts[1] : ""
    }
})

basic.forever(function () {
    if (cfgWanted) {
        cfgWanted = false
        cfgTxPos = 0
        cfgTxActive = true
        bluetooth.uartWriteLine("CFGBEGIN")
        cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
    }

    if (cfgTxActive && input.runningTime() >= cfgTxNextAt) {
        if (cfgTxPos < CFG.length) {
            bluetooth.uartWriteLine("CFG " + CFG.substr(cfgTxPos, 18))
            cfgTxPos += 18
            cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
        } else {
            bluetooth.uartWriteLine("CFGEND")
            cfgTxActive = false
        }
    }

    if (input.runningTime() >= nextPollAt) {
        nextPollAt = input.runningTime() + POLL_MS
        let l = mecanumRobotV2.LineTracking(LT.Left)
        let c = mecanumRobotV2.LineTracking(LT.Center)
        let r = mecanumRobotV2.LineTracking(LT.Right)
        // On change only: these sit still most of the time.
        if (l != lastL) {
            lastL = l
            bluetooth.uartWriteLine("UPD ln_l " + l)
        }
        if (c != lastC) {
            lastC = c
            bluetooth.uartWriteLine("UPD ln_c " + c)
        }
        if (r != lastR) {
            lastR = r
            bluetooth.uartWriteLine("UPD ln_r " + r)
        }
    }

    basic.pause(5)
})

bluetooth.onBluetoothConnected(function () {
    mecanumRobotV2.setLed(LedCount.Left, LedState.ON)
})

bluetooth.onBluetoothDisconnected(function () {
    mecanumRobotV2.setLed(LedCount.Left, LedState.OFF)
})
