/**
 * TEST: HEADLIGHTS, DRIVEN FROM THE APP - flash this alone.
 *
 * Extensions: mecanum_robot_v2, bluetooth
 *
 * The app-driven twin of test-leds.ts. That one runs a fixed sequence while you
 * watch; this one hands the subsystem to a child through the phone.
 *
 * Open the app, press Connect, and the HEADLIGHTS panel appears by itself. The
 * layout lives in this file and is sent over the link -- nothing to import.
 *
 * PASS: each switch turns its lamp on and off.
 * FAIL: panel never appears -> run test-app-ble.ts first. That is a link
 *                             fault, not a lamp fault.
 *       panel appears but nothing happens -> run test-leds.ts, which removes
 *                             Bluetooth from the picture entirely.
 */

// Generated by tests/gen_test_layouts.py. Widget ids match main.ts on purpose,
// so the handlers below are the real ones rather than lookalikes.
const CFG = "eyJ0aXRsZSI6Ik1lY2FudW0gLSBIZWFkbGlnaHRzIHRlc3QiLCJ3aWRnZXRzIjpbeyJpZCI6ImdycF90ZXN0IiwidCI6Imdyb3VwIiwibGFiZWwiOiJIRUFETElHSFRTIiwiY29sb3IiOiIjZmJiZjI0IiwieCI6NTYsInkiOjQyLCJ3IjozODgsImgiOjIyMiwiY2hpbGRyZW4iOlsidG9nZ2xlX2xlZF9sIiwidG9nZ2xlX2xlZF9yIl19LHsiaWQiOiJ0b2dnbGVfbGVkX2wiLCJ0IjoidG9nZ2xlIiwieCI6ODAsInkiOjEwMCwidyI6MTYwLCJoIjoxNDAsImxhYmVsIjoiTGVmdCBsYW1wIiwiZ3JvdXBJZCI6ImdycF90ZXN0In0seyJpZCI6InRvZ2dsZV9sZWRfciIsInQiOiJ0b2dnbGUiLCJ4IjoyNjAsInkiOjEwMCwidyI6MTYwLCJoIjoxNDAsImxhYmVsIjoiUmlnaHQgbGFtcCIsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJsYmxfaGludCIsInQiOiJsYWJlbCIsIngiOjgwLCJ5IjoyODAsInciOjM0MCwiaCI6NzAsImxhYmVsIjoiU3dpdGNoIGVhY2ggbGFtcCBvbiBhbmQgb2ZmLiBUaGV5IGFyZSB0aGUgY2hlYXBlc3QgdGhpbmcgb24gdGhlIHJvYm90LiIsInZhbHVlIjoiU3dpdGNoIGVhY2ggbGFtcCBvbiBhbmQgb2ZmLiBUaGV5IGFyZSB0aGUgY2hlYXBlc3QgdGhpbmcgb24gdGhlIHJvYm90LiIsIm1vZGVsIjoiY2FyZCJ9XSwiY2FudmFzIjp7InciOjUwMCwiaCI6NDA2fX0="

bluetooth.startUartService()
bluetooth.setTransmitPower(7)

let cfgWanted = false
let cfgTxPos = 0
let cfgTxActive = false
let cfgTxNextAt = 0
let nextPollAt = 0
const CFG_TX_GAP_MS = 35
const POLL_MS = 0

// Only ever sets flags and drives hardware. The CFG burst is NOT sent from
// here -- see the forever loop below.
bluetooth.onUartDataReceived(serial.delimiters(Delimiters.NewLine), function () {
    let cmd = bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine))
    // Chained if/else-if with no `return` inside this lambda, matching the
    // shape main.ts uses. Getting here took two wrong guesses at a MakeCode
    // "!!proc || !bin.finalPass" error that points at the line below and says
    // nothing useful; what actually broke the build was a syntax error further
    // down. This shape is kept because it matches the firmware that is known
    // to compile, NOT because early returns are proven to cause that error.
    if (cmd == "GETCFG") {
        cfgWanted = true
    }
    else if (cmd.indexOf("SET ") == 0) {
        let parts = cmd.substr(4).split(" ")
        let id = parts[0]
        let val = parts.length > 1 ? parts[1] : ""
        if (id == "toggle_led_l") {
            mecanumRobotV2.setLed(LedCount.Left, val == "1" ? LedState.ON : LedState.OFF)
        }
        else if (id == "toggle_led_r") {
            mecanumRobotV2.setLed(LedCount.Right, val == "1" ? LedState.ON : LedState.OFF)
        }
    }
})

basic.forever(function () {
    if (cfgWanted) {
        cfgWanted = false
        cfgTxPos = 0
        cfgTxActive = true
        bluetooth.uartWriteLine("CFGBEGIN")
        cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
    }

    if (cfgTxActive && input.runningTime() >= cfgTxNextAt) {
        if (cfgTxPos < CFG.length) {
            bluetooth.uartWriteLine("CFG " + CFG.substr(cfgTxPos, 18))
            cfgTxPos += 18
            cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
        } else {
            bluetooth.uartWriteLine("CFGEND")
            cfgTxActive = false
        }
    }

    basic.pause(5)
})

bluetooth.onBluetoothConnected(function () {
    basic.showIcon(IconNames.Yes)
})

bluetooth.onBluetoothDisconnected(function () {
    mecanumRobotV2.setLed(LedCount.Left, LedState.OFF)
    mecanumRobotV2.setLed(LedCount.Right, LedState.OFF)
    basic.showIcon(IconNames.No)
})

basic.showString("LED")
