/**
 * TEST: ULTRASONIC, DRIVEN FROM THE APP - flash this alone.
 *
 * Extensions: mecanum_robot_v2, bluetooth
 *
 * The app-driven twin of test-ultrasonic.ts. That one runs a fixed sequence while you
 * watch; this one hands the subsystem to a child through the phone.
 *
 * Open the app, press Connect, and the DISTANCE panel appears by itself. The
 * layout lives in this file and is sent over the link -- nothing to import.
 *
 * PASS: the number and the graph follow your hand, and Obstacle pops up close in.
 * FAIL: panel never appears -> run test-app-ble.ts first. That is a link
 *                             fault, not a sensor fault.
 *       panel appears but nothing happens -> run test-ultrasonic.ts, which removes
 *                             Bluetooth from the picture entirely.
 */

// Generated by tests/gen_test_layouts.py. Widget ids match main.ts on purpose,
// so the handlers below are the real ones rather than lookalikes.
const CFG = "eyJ0aXRsZSI6Ik1lY2FudW0gLSBEaXN0YW5jZSB0ZXN0Iiwid2lkZ2V0cyI6W3siaWQiOiJncnBfdGVzdCIsInQiOiJncm91cCIsImxhYmVsIjoiRElTVEFOQ0UiLCJjb2xvciI6IiNmZmIwMjAiLCJ4Ijo1NiwieSI6NDIsInciOjQ2OCwiaCI6NTYyLCJjaGlsZHJlbiI6WyJnYXVnZV9kaXN0IiwiYWxlcnQiLCJncmFwaF9kaXN0Il19LHsiaWQiOiJnYXVnZV9kaXN0IiwidCI6ImdhdWdlIiwieCI6ODAsInkiOjEwMCwidyI6MjIwLCJoIjoyMDAsImxhYmVsIjoiRGlzdGFuY2UiLCJtaW4iOjAsIm1heCI6MjAwLCJ1bml0cyI6ImNtIiwiZGVjaW1hbHMiOjAsIm1vZGVsIjoiY2xhc3NpYyIsImdyb3VwSWQiOiJncnBfdGVzdCJ9LHsiaWQiOiJhbGVydCIsInQiOiJub3RpZmljYXRpb24iLCJ4IjozMzAsInkiOjExMCwidyI6MTEwLCJoIjoxODAsImxhYmVsIjoiT2JzdGFjbGUiLCJncm91cElkIjoiZ3JwX3Rlc3QifSx7ImlkIjoiZ3JhcGhfZGlzdCIsInQiOiJncmFwaCIsIngiOjgwLCJ5IjozNDAsInciOjQyMCwiaCI6MjQwLCJsYWJlbCI6IkRpc3RhbmNlIGNtIiwibW9kZWwiOiJncmlkIiwid2luZG93U2VjIjozMCwic2VyaWVzIjoxLCJncm91cElkIjoiZ3JwX3Rlc3QifSx7ImlkIjoibGJsX2hpbnQiLCJ0IjoibGFiZWwiLCJ4Ijo4MCwieSI6NjIwLCJ3Ijo0MjAsImgiOjcwLCJsYWJlbCI6Ik1vdmUgeW91ciBoYW5kIGluIGZyb250IG9mIHRoZSBzZW5zb3IgYW5kIHdhdGNoIHRoZSBsaW5lIG1vdmUuIiwidmFsdWUiOiJNb3ZlIHlvdXIgaGFuZCBpbiBmcm9udCBvZiB0aGUgc2Vuc29yIGFuZCB3YXRjaCB0aGUgbGluZSBtb3ZlLiIsIm1vZGVsIjoiY2FyZCJ9XSwiY2FudmFzIjp7InciOjU4MCwiaCI6NzQ2fX0="

bluetooth.startUartService()
bluetooth.setTransmitPower(7)

let cfgWanted = false
let cfgTxPos = 0
let cfgTxActive = false
let cfgTxNextAt = 0
let nextPollAt = 0
const CFG_TX_GAP_MS = 35
const POLL_MS = 300

// main.ts warns that ultra() BUSY-WAITS: a missing echo costs ~250ms and
// freezes the whole runtime, not just this loop. Polling slowly is deliberate.
let lastAlertAt = 0

// Only ever sets flags and drives hardware. The CFG burst is NOT sent from
// here -- see the forever loop below.
bluetooth.onUartDataReceived(serial.delimiters(Delimiters.NewLine), function () {
    let cmd = bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine))
    // Chained if/else-if with no `return` inside this lambda, matching the
    // shape main.ts uses. Getting here took two wrong guesses at a MakeCode
    // "!!proc || !bin.finalPass" error that points at the line below and says
    // nothing useful; what actually broke the build was a syntax error further
    // down. This shape is kept because it matches the firmware that is known
    // to compile, NOT because early returns are proven to cause that error.
    if (cmd == "GETCFG") {
        cfgWanted = true
    }
    else if (cmd.indexOf("SET ") == 0) {
        let parts = cmd.substr(4).split(" ")
        let id = parts[0]
        let val = parts.length > 1 ? parts[1] : ""
    }
})

basic.forever(function () {
    if (cfgWanted) {
        cfgWanted = false
        cfgTxPos = 0
        cfgTxActive = true
        bluetooth.uartWriteLine("CFGBEGIN")
        cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
    }

    if (cfgTxActive && input.runningTime() >= cfgTxNextAt) {
        if (cfgTxPos < CFG.length) {
            bluetooth.uartWriteLine("CFG " + CFG.substr(cfgTxPos, 18))
            cfgTxPos += 18
            cfgTxNextAt = input.runningTime() + CFG_TX_GAP_MS
        } else {
            bluetooth.uartWriteLine("CFGEND")
            cfgTxActive = false
        }
    }

    if (input.runningTime() >= nextPollAt) {
        nextPollAt = input.runningTime() + POLL_MS
        let d = mecanumRobotV2.ultra()
        if (d > 0) {
            bluetooth.uartWriteLine("UPD gauge_dist " + d)
            bluetooth.uartWriteLine("UPD graph_dist " + d)
            // Edge-triggered with a cool-down: the app raises a toast per
            // message, so repeating it every poll would bury the screen.
            if (d < 20 && input.runningTime() - lastAlertAt > 3000) {
                lastAlertAt = input.runningTime()
                bluetooth.uartWriteLine("UPD alert Obstacle " + d + "cm")
            }
        }
    }

    basic.pause(5)
})

bluetooth.onBluetoothConnected(function () {
    basic.showIcon(IconNames.Yes)
})

bluetooth.onBluetoothDisconnected(function () {
    basic.showIcon(IconNames.No)
})

basic.showString("DST")
